# Protocol for Web services | Pre-fabricated image with Apache installed
FROM httpd:latest

# File created OUTSIDE of the site | Standard place to host Apache sites
COPY index.html /usr/local/apache2/htdocs/

# Standard port for Web services
EXPOSE 80